services:
  blog-post-db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog-post
    ports:
      - 5432:5432
    volumes:
      - blog-post-db-volume:/var/lib/postgresql/data
      - $PWD/infra/db/tables.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  blog-post-db-volume:
